prints the last k lines in k_strings.txt file attached - added a chec…
careercup/CtCI-6th-Edition-cpp pull request #32
Opened 2017-03-05 13:44 UTC by kohn1001

…k to eliminate empty strings
Without this check it actually doesn't print the last k lines - (tested on Mac)

2017-06-09 08:00 UTC, kohn1001 commented
Much better version - building a vector of size K (in case K is much larger then the number of lines in file - it's much more efficient)

2022-09-02 06:20 UTC, sergio-nsk requested changes

2022-09-02 06:20 UTC, sergio-nsk commented on Chapter-16-moderate/word_freq.cpp
> +	transform(word.begin(), word.end(), tword.begin(), ::tolower);
Transform to the empty target destination crashes the app.

2022-09-02 06:20 UTC, sergio-nsk commented on Ch 1.Arrays And Strings/3.URLify/URLify2.cpp
> +using namespace std;
Very bad habit.
[Why is "using namespace std;" considered bad practice?](https://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice)

2022-09-02 06:20 UTC, sergio-nsk commented on Ch 12. C++/print_k_lines.cpp
> +using namespace std;
Very bad habit.
[Why is "using namespace std;" considered bad practice?](https://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice)

2022-09-02 06:20 UTC, sergio-nsk commented on Chapter-16-moderate/word_freq.cpp
> +using namespace std;
Very bad habit.
[Why is "using namespace std;" considered bad practice?](https://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice)

2022-09-02 06:20 UTC, sergio-nsk commented on Chapter-16-moderate/word_freq.cpp
> +	if (!wordFreq.empty()) {
Redundant if just after created empty `wordFreq`.

2022-09-02 06:20 UTC, sergio-nsk commented on Chapter-16-moderate/word_freq.cpp
> +	return wordFreq[word];
You placed lowercased words into the map, `word` can has capital letters.

2022-10-16 19:47 UTC, merged

2022-10-16 20:15 UTC, sergio-nsk commented
@KrishMunot Why have you approved and merged the PR containing many bugs? Especially the crash/undefined behavior by [`std::transform()` to the empty container](https://github.com/careercup/CtCI-6th-Edition-cpp/pull/32#discussion_r961317756)?

2022-10-16 21:24 UTC, KrishMunot commented
My bad, feel free to revert it, i thought some of the commits were valid.
Please revert it.

On Mon, Oct 17, 2022, 01:46 Sergey ***@***.***> wrote:

> @KrishMunot <https://github.com/KrishMunot> Why have you approved and
> merged the PR containing many bugs? Especially the crash/undefined behavior
> by std::transform() to the empty container
> <https://github.com/careercup/CtCI-6th-Edition-cpp/pull/32#discussion_r961317756>
> ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/careercup/CtCI-6th-Edition-cpp/pull/32#issuecomment-1280047955>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA7YAUK7E54QMZYBN7RJPVDWDRPABANCNFSM4DCNVHDA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-17 06:13 UTC, sergio-nsk commented
I can revert it, but it will require your approve, since I have not right to merge.

2022-10-17 06:37 UTC, KrishMunot commented
Sure, no problem. I'll approve it.

On Mon, Oct 17, 2022, 11:43 Sergey ***@***.***> wrote:

> I can revert it, but it will require your approve, since I have not right
> to merge.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/careercup/CtCI-6th-Edition-cpp/pull/32#issuecomment-1280339776>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA7YAUNMA7DAP23J4HTOHP3WDTU77ANCNFSM4DCNVHDA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>